name: CD-to-DockerHub
on:
  push:
    branches: [ main ]

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Create timestamp
      run: echo "TS=$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_ENV

    - name: Build image
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/lab6-nodejs
        docker build -t $IMAGE:latest .

    - name: Tag images
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/lab6-nodejs
        docker tag $IMAGE:latest $IMAGE:${{ github.sha }}
        docker tag $IMAGE:latest $IMAGE:${{ env.TS }}

    - name: Push images
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/lab6-nodejs
        docker push $IMAGE:latest
        docker push $IMAGE:${{ github.sha }}
        docker push $IMAGE:${{ env.TS }}
